// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TinyUrlNintexAssignment.Data;

namespace TinyUrlNintexAssignment.Migrations
{
    [DbContext(typeof(TinyUrlContext))]
    partial class TinyUrlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("TinyUrlNintexAssignment.Models.TinyUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OriginalUrl")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TinyUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
